apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rhg-data-scratch-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Pi
  volumeName: jhub-rhg-data-scratch-pv
  storageClassName: rhg-us-west1-scratch
