apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: inventory-gcs-bucket
  annotations:
    workflows.argoproj.io/description: >-
      Parses objects in a GCS bucket, outputting table of metadata into a BigQuery Dataset.
    workflows.argoproj.io/tags: gcs,bq,inventory,operations
    workflows.argoproj.io/version: '>= 3.1.0'
  labels:
    workflows.rhgresearch.com/project: operations
spec:
  workflowMetadata:
    labels:
      workflows.rhgresearch.com/project: operations
    annotations:
      workflows.argoproj.io/description: >-
        Parses objects in a GCS bucket, outputting table of metadata into a BigQuery Dataset.
  entrypoint: bucket2bq
  arguments:
    parameters:
      - name: bucket
      - name: bq-project
        value: "rhg-hub"
      - name: bq-dataset
        value: "bucketinventory"
      - name: bq-table
        value: "{{ workflow.parameters.bucket }}"
      - name: bq-location
        value: "us-west1"
      - name: scratch-bucket
        value: "rhg-data-scratch"
  templates:

    - name: bucket2bq
      inputs:
        parameters:
          - name: bucket
          - name: bq-project
          - name: bq-dataset
          - name: bq-table
          - name: bq-location
          - name: scratch-bucket
      container:
        image: ghcr.io/brews/bucket2bq:0.3.0
        env:
          - name: BUCKET2BQ_BUCKET
            value: "{{ inputs.parameters.bucket }}"
          - name: BUCKET2BQ_PROJECT
            value: "{{ inputs.parameters.bq-project }}"
          - name: BUCKET2BQ_DATASET
            value: "{{ inputs.parameters.bq-dataset }}"
          - name: BUCKET2BQ_TABLE
            value: "{{ inputs.parameters.bq-table }}"
          - name: BUCKET2BQ_SCRATCH_BUCKET
            value: "{{ inputs.parameters.scratch-bucket }}"
          - name: BUCKET2BQ_LOCATION
            value: "{{ inputs.parameters.bq-location }}"
        command: [ /run.sh ]
        securityContext:
          runAsUser: 1000
        resources:
          limits:
            cpu: "2"
            memory: "1Gi"
          requests:
            cpu: "0.5"
            memory: "500Mi"